name: Build and deploy Python app to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip freeze > requirements_lock.txt

    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        echo "Checking startup.sh permissions..."
        chmod +x startup.sh
        echo "Creating deployment structure..."
        mkdir -p deploy
        cp -r app deploy/
        cp requirements.txt deploy/
        cp startup.sh deploy/
        cd deploy
        zip -r ../deploy.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Verity'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy.zip
        clean: true