name: Deploy to Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Verity-AI'
        slot-name: 'Production'
        startup-command: 'sh startup.sh'  # Changed to use startup script
        package: .  # Changed to deploy entire directory

    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        chmod +x startup.sh
        zip -r deploy.zip . -x "*.git*" "*.venv*"
        echo "Package created"